# Generated by Django 5.2.6 on 2025-10-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('placa_carro', models.CharField(blank=True, max_length=10, verbose_name='Placa do Carro')),
                ('modelo_carro', models.CharField(blank=True, max_length=50, verbose_name='Modelo do Carro')),
                ('cor_carro', models.CharField(blank=True, max_length=30, verbose_name='Cor do Carro')),
                ('ativo', models.BooleanField(default=True, help_text='Marque se o guia está disponível para novos passeios')),
            ],
        ),
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('imagem', models.ImageField(upload_to='praias/')),
                ('slug', models.SlugField(help_text='URL amigável, ex: praia-do-gunga', unique=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do passeio por pessoa', max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL amigável gerada a partir do título.', max_length=200, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='transfers/')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mais_vendido', models.BooleanField(default=False, help_text="Marque esta opção para destacar este transfer como 'Mais Vendido'.")),
                ('direcao', models.CharField(choices=[('ida', 'Ida (Aeroporto -> Maceió)'), ('volta', 'Volta (Maceió -> Aeroporto)'), ('ida_e_volta', 'Ida e Volta'), ('outros', 'Outros')], default='outros', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='carrossel/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('praia_link', models.ForeignKey(blank=True, help_text='Opcional: Selecione uma praia para que o banner se torne um link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.praia')),
            ],
        ),
    ]
