# Generated by Django 5.2.6 on 2025-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='destino',
            field=models.CharField(default='', help_text='Ex: Hotéis na Orla (Pajuçara)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='origem',
            field=models.CharField(default='', help_text='Ex: Aeroporto de Maceió (MCZ)', max_length=100),
            preserve_default=False,
        ),
    ]
