# Generated by Django 5.2.6 on 2026-01-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemcarrossel',
            name='transfer_link',
            field=models.ForeignKey(blank=True, help_text='Opcional: Selecione um transfer para que o banner leve para o agendamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transfer'),
        ),
    ]
