# Generated by Django 5.2.6 on 2026-01-25 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_imagemcarrossel_transfer_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemcarrossel',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.AddField(
            model_name='imagemcarrossel',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemcarrossel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='legenda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='praia_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.praia', verbose_name='Ligar a um Passeio'),
        ),
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='transfer_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transfer', verbose_name='Ligar a um Transfer'),
        ),
    ]
