# Generated by Django 5.2.6 on 2026-02-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ativa_imagemcarrossel_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guia', verbose_name='Guia Responsável'),
        ),
    ]
