# Generated by Django 5.2.6 on 2026-02-03 02:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reserva_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo',
            field=models.CharField(default=core.models.gerar_codigo_reserva, editable=False, max_length=10, unique=True),
        ),
    ]
