# Generated by Django 5.2.6 on 2026-03-27 23:05

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reserva_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='praia',
            name='tipo_etiqueta',
            field=models.CharField(choices=[('norte', '🌴 Litoral Norte'), ('sul', '🌊 Litoral Sul'), ('destaque', '⭐ Mais Procurado'), ('promocao', '🔥 Oferta Especial'), ('privativo', '🚗 Passeio Privativo')], default='norte', max_length=20, verbose_name='Selo do Card'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status_pagamento_comissao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comissão do Parceiro'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='praia',
            name='descricao_longa',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='descricao_longa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='origem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('chave_pix', models.CharField(blank=True, help_text='Chave Pix para receber comissões', max_length=100, null=True)),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentagem padrão (%)', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.parceiro'),
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data Bloqueada')),
                ('motivo', models.CharField(default='Vagas Esgotadas', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('praia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.praia', verbose_name='Passeio Específico')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('data', 'praia')},
            },
        ),
    ]
