# Generated by Django 5.2.6 on 2026-03-28 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_praia_tipo_etiqueta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('novo', 'Novo Lead'), ('contato', 'Em Contato'), ('orcamento', 'Orçamento Enviado'), ('fechado', 'Venda Concluída'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('valor_proposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('praia_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.praia')),
            ],
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('novo', 'Novo Lead (Site)'), ('contato', 'Em Contato/Zap'), ('orcamento', 'Orçamento Enviado'), ('fechado', 'Venda Concluída'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('praia_interesse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.praia')),
            ],
        ),
    ]
