# Generated by Django 5.2.6 on 2026-03-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lead_negociacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='categoria',
            field=models.CharField(choices=[('passeio', 'Passeio'), ('transfer', 'Transfer'), ('pacote', 'Pacote Completo')], default='passeio', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
