# Generated by Django 5.2.6 on 2026-03-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lead_categoria_lead_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade_origem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Origem'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço/Hotel'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Notas sobre o Cliente'),
        ),
    ]
