# Generated by Django 5.2.6 on 2025-10-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Serviço (R$)')),
                ('tipo', models.CharField(choices=[('transfer', 'Transfer'), ('passeio', 'Passeio')], max_length=10)),
                ('data_agendamento', models.DateTimeField()),
                ('local_partida', models.CharField(help_text='Aeroporto, Hotel, etc.', max_length=255)),
                ('local_chegada', models.CharField(blank=True, max_length=255)),
                ('numero_passageiros', models.PositiveIntegerField()),
                ('informacoes_voo', models.CharField(blank=True, help_text='Cia Aérea e Número do Voo', max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('guia_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.guia')),
                ('praia_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.praia')),
            ],
        ),
    ]
