# Generated by Django 5.2.6 on 2025-10-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True, verbose_name='Número da Reserva'),
        ),
    ]
