# Generated by Django 5.2.6 on 2026-01-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_numero_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
